### ISSUE TITLE
build.sh  occurs Error

### ISSUE THREAD

**Issue by m-dake** [mimirblockchainsolutions/flutter-rust-middleware#3]
To change the file lib.rs and run build.sh are occurs error
```
ln: ../ios/Flutter/libmiddleware.a: File exists
```

**Comment by m-dake** [comment]
I will make PR wait for mininutes
```
ln -s
↓
ln -snf
```

**Comment by mdk-aza** [comment]
https://github.com/mimirblockchainsolutions/flutter-rust-middleware/pull/4

**Comment by nickfierro** [comment]
Merged
